import { useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { AdminFrame, AdminInput, AdminSelect, safeError } from "./_common";
import { Button, Card, EmptyState, ErrorState, LoadingState } from "../../components/ui";
import { trpc } from "../../lib/trpc";
import { useTheme } from "../../lib/theme";
export default function Assessments() {
  const { colors } = useTheme(); const utils = trpc.useUtils(); const q = trpc.admin.assessmentsList.useQuery(); const bank = trpc.admin.questionsBankList.useQuery(); const levels = trpc.admin.levelThresholds.useQuery();
  const [tab, setTab] = useState<"assessments" | "bank">("assessments"); const [name, setName] = useState(""); const [levelId, setLevelId] = useState(""); const [pass, setPass] = useState("70"); const [maxAttempts, setMaxAttempts] = useState("3"); const [duration, setDuration] = useState("15"); const [question, setQuestion] = useState(""); const [questionType, setQuestionType] = useState<"mcq" | "true_false" | "fill_blank" | "recitation">("mcq"); const [options, setOptions] = useState(""); const [answer, setAnswer] = useState(""); const [topic, setTopic] = useState(""); const [selectedAssessment, setSelectedAssessment] = useState<any>(null); const [feedback, setFeedback] = useState("");
  const attempts = trpc.admin.attemptsList.useQuery({ assessmentId: selectedAssessment?.id ?? "" }, { enabled: !!selectedAssessment });
  const done = (s: string) => ({ onSuccess: () => { setFeedback(s); setName(""); setQuestion(""); setOptions(""); setAnswer(""); setTopic(""); void utils.admin.assessmentsList.invalidate(); void utils.admin.questionsBankList.invalidate(); }, onError: (e: unknown) => setFeedback(safeError(e, "تعذر تنفيذ العملية.")) });
  const create = trpc.admin.assessmentCreate.useMutation(done("أُنشئ الاختبار")); const toggle = trpc.admin.assessmentUpdate.useMutation(done("حُدّث الاختبار")); const add = trpc.admin.questionAdd.useMutation(done("أُضيف السؤال"));
  if (q.isLoading || bank.isLoading || levels.isLoading) return <AdminFrame title="التقييمات"><LoadingState /></AdminFrame>; if (q.error || bank.error || levels.error) return <AdminFrame title="التقييمات"><ErrorState onRetry={() => { void q.refetch(); void bank.refetch(); void levels.refetch(); }} /></AdminFrame>;
  const rows: any[] = Array.isArray(q.data) ? q.data : []; return <AdminFrame title="التقييمات"><Text style={[styles.feedback, { color: colors.primary }]}>{feedback}</Text>
      <Card><AdminInput value={name} onChangeText={setName} placeholder="اسم الاختبار (3 أحرف على الأقل)" /><AdminSelect label="المستوى (اختياري)" value={levelId} options={(levels.data ?? []).map((l: any) => ({ value: String(l.id), label: String(l.name) }))} onChange={setLevelId} placeholder="بدون مستوى محدد" /><View style={styles.inline}><AdminInput value={pass} onChangeText={setPass} placeholder="نسبة النجاح" keyboardType="number-pad" /><AdminInput value={maxAttempts} onChangeText={setMaxAttempts} placeholder="عدد المحاولات" keyboardType="number-pad" /><AdminInput value={duration} onChangeText={setDuration} placeholder="الدقائق" keyboardType="number-pad" /></View><Button label="إنشاء اختبار" disabled={name.trim().length < 3 || create.isPending} loading={create.isPending} onPress={() => create.mutate({ name: name.trim(), levelId: levelId ? Number(levelId) : undefined, passPercentage: Number(pass), maxAttempts: Number(maxAttempts), durationMinutes: Number(duration) } as any)} /></Card>
      <View style={styles.typeRow}><Button label="الاختبارات" variant={tab === "assessments" ? "primary" : "secondary"} onPress={() => setTab("assessments")} /><Button label={`بنك الأسئلة (${bank.data?.length ?? 0})`} variant={tab === "bank" ? "primary" : "secondary"} onPress={() => setTab("bank")} /></View>
      {tab === "bank" ? <Card><Text style={[styles.name, { color: colors.text }]}>إضافة سؤال إلى البنك العام</Text><AdminInput value={question} onChangeText={setQuestion} placeholder="نص سؤال جديد" multiline /><View style={styles.typeRow}>{(["mcq", "true_false", "fill_blank", "recitation"] as const).map((type) => <Button key={type} label={type === "mcq" ? "اختيارات" : type === "true_false" ? "صح/خطأ" : type === "fill_blank" ? "فراغ" : "تلاوة"} variant={questionType === type ? "primary" : "secondary"} onPress={() => setQuestionType(type)} />)}</View>{questionType === "mcq" ? <AdminInput value={options} onChangeText={setOptions} placeholder="الخيارات مفصولة بفاصلة" /> : null}<AdminInput value={answer} onChangeText={setAnswer} placeholder="الإجابة الصحيحة (اختياري)" /><AdminInput value={topic} onChangeText={setTopic} placeholder="الموضوع (اختياري)" /><Button label="إضافة إلى البنك" disabled={question.trim().length < 3 || add.isPending} loading={add.isPending} onPress={() => add.mutate({ assessmentId: undefined, questionText: question.trim(), type: questionType, options: questionType === "mcq" ? options.split(",").map((x) => x.trim()).filter(Boolean) : undefined, correctAnswer: answer.trim() || undefined, topic: topic.trim() || undefined, isBankQuestion: true } as any)} /></Card> : null}
     {tab === "bank" ? (!bank.data?.length ? <EmptyState title="بنك الأسئلة فارغ" /> : bank.data.map((item: any) => <Card key={item.id}><Text style={[styles.name, { color: colors.text }]}>{item.questionText}</Text><Text style={[styles.muted, { color: colors.muted }]}>{item.topic ?? ""} · {item.type}</Text>{rows.map((a) => <Button key={a.id} label={`إضافة إلى ${a.name}`} variant="secondary" onPress={() => add.mutate({ assessmentId: a.id, questionText: item.questionText, type: item.type, options: item.options ?? undefined, correctAnswer: item.correctAnswer ?? undefined, topic: item.topic ?? undefined })} />)}</Card>)) : (!rows.length ? <EmptyState title="لا توجد اختبارات" /> : rows.map((a) => <Card key={a.id}><Text style={[styles.name, { color: colors.text }]}>{a.name}</Text><Text style={[styles.muted, { color: colors.muted }]}>{a.levelName ? `المستوى: ${a.levelName} · ` : ""}نجاح {a.passPercentage}% · {a.maxAttempts} محاولات · {a.questionCount ?? 0} سؤال · {a.attemptCount ?? 0} محاولة</Text><View style={styles.actions}><Button label={a.isActive === false ? "تفعيل" : "إيقاف"} variant="secondary" onPress={() => toggle.mutate({ id: a.id, isActive: a.isActive === false } as any)} /><Button label={`النتائج (${a.attemptCount ?? 0})`} variant="secondary" onPress={() => setSelectedAssessment(a)} /><AdminInput value={question} onChangeText={setQuestion} placeholder="نص سؤال جديد" multiline /><View style={styles.typeRow}>{(["mcq", "true_false", "fill_blank", "recitation"] as const).map((type) => <Button key={type} label={type === "mcq" ? "اختيارات" : type === "true_false" ? "صح/خطأ" : type === "fill_blank" ? "فراغ" : "تلاوة"} variant={questionType === type ? "primary" : "secondary"} onPress={() => setQuestionType(type)} />)}</View>{questionType === "mcq" ? <AdminInput value={options} onChangeText={setOptions} placeholder="الخيارات مفصولة بفاصلة" /> : null}<AdminInput value={answer} onChangeText={setAnswer} placeholder="الإجابة الصحيحة (اختياري)" /><AdminInput value={topic} onChangeText={setTopic} placeholder="الموضوع (اختياري)" /><Button label="إضافة السؤال" disabled={question.trim().length < 3 || add.isPending} loading={add.isPending} onPress={() => add.mutate({ assessmentId: a.id, questionText: question.trim(), type: questionType, options: questionType === "mcq" ? options.split(",").map((x) => x.trim()).filter(Boolean) : undefined, correctAnswer: answer.trim() || undefined, topic: topic.trim() || undefined } as any)} /></View></Card>))}
    {selectedAssessment ? <Card><Text style={[styles.name, { color: colors.text }]}>نتائج: {selectedAssessment.name}</Text>{attempts.isLoading ? <LoadingState /> : attempts.error ? <ErrorState onRetry={() => void attempts.refetch()} /> : !attempts.data?.length ? <EmptyState title="لا توجد محاولات" /> : attempts.data.map((item: any) => <View key={item.id} style={styles.attempt}><Text style={[styles.name, { color: colors.text }]}>{item.studentName ?? "طالب"} · {item.score ?? 0}%</Text><Text style={[styles.muted, { color: colors.muted }]}>{item.passed ? "ناجح" : "راسب"} · {String(item.createdAt ?? "")}</Text></View>)}<Button label="إغلاق النتائج" variant="secondary" onPress={() => setSelectedAssessment(null)} /></Card> : null}
  </AdminFrame>;
}
const styles = StyleSheet.create({ name: { fontFamily: "IBMPlexSansArabic_700Bold", fontSize: 16, textAlign: "right" }, muted: { fontFamily: "IBMPlexSansArabic_400Regular", fontSize: 12, textAlign: "right" }, actions: { gap: 7, marginTop: 8 }, inline: { flexDirection: "row", gap: 6 }, typeRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 }, attempt: { borderTopWidth: StyleSheet.hairlineWidth, paddingTop: 8, marginTop: 8 }, feedback: { textAlign: "right", marginBottom: 8, fontFamily: "IBMPlexSansArabic_600SemiBold", fontSize: 12 } });