import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { AdminFrame } from "./_common";
import { Badge, Card, EmptyState, ErrorState, LoadingState } from "../../components/ui";
import { trpc } from "../../lib/trpc";
import { useTheme } from "../../lib/theme";

const actions: Record<string, string> = { login: "تسجيل دخول للوحة الإشراف", create_supervisor: "إنشاء مشرف", create_teacher: "إنشاء معلم", activate_account: "تنشيط حساب", deactivate_account: "إيقاف حساب", reset_account_password: "إعادة تعيين كلمة سر", terminate_account_sessions: "إنهاء جلسات حساب", force_logout_admin: "إنهاء جلسة مشرف", change_master_password: "تغيير كلمة المرور الرئيسية", update_setting: "تعديل إعداد", message_user: "مراسلة مستخدم", warn_user: "تحذير مستخدم", ban_user: "حظر مستخدم", delete_user: "حذف مستخدم", soft_delete_teacher: "حذف معلم (أرشفة)", create_schedule: "إنشاء جدول", activate_schedule: "تنشيط جدول", deactivate_schedule: "إيقاف جدول", delete_schedule: "حذف جدول", open_schedule_booking: "فتح الحجز لجدول", close_schedule_booking: "إغلاق الحجز لجدول", cancel_booking: "إلغاء حجز", create_level: "إنشاء مستوى", update_level: "تعديل مستوى", delete_level: "حذف مستوى", swap_level_order: "تبديل ترتيب مستويين", approve_promotion: "اعتماد ترقية", reject_promotion: "رفض ترقية", approve_qiraat: "اعتماد إجازة قراءات", reject_qiraat: "رفض إجازة قراءات", review_placement: "مراجعة اختبار تحديد مستوى", request_teacher_info: "طلب معلومات من معلم", approve_teacher: "اعتماد معلم", reject_teacher: "رفض معلم", assign_fatwa: "إسناد فتوى", update_fatwa_category: "تعديل تصنيف فتوى", fatwa_answer_approve: "اعتماد جواب فتوى", fatwa_answer_reject: "رفض جواب فتوى", reject_fatwa_question: "رفض سؤال فتوى", assign_mufti: "تعيين مفتٍ", unassign_mufti: "إلغاء تعيين مفتٍ", create_book: "إضافة كتاب", update_book: "تعديل كتاب", delete_book: "حذف كتاب", archive_book: "أرشفة كتاب", restore_book: "استعادة كتاب", create_assessment: "إنشاء تقييم", update_assessment: "تعديل تقييم", add_question: "إضافة سؤال لتقييم", add_questions: "إضافة أسئلة لتقييم", send_notification: "إرسال إشعار", enable_recurring_notification: "تفعيل إشعار متكرر", disable_recurring_notification: "إيقاف إشعار متكرر" };
const targets: Record<string, string> = { user: "مستخدم", student: "طالب", teacher: "معلم", session: "جلسة", weekly_schedule: "جدول أسبوعي", level: "مستوى", promotion_request: "طلب ترقية", qiraat_certificate: "إجازة قراءات", fatwa_question: "سؤال فتوى", fatwa_answer: "جواب فتوى", book: "كتاب", assessment: "تقييم", notification: "إشعار", system_setting: "إعداد نظام", admin_session: "جلسة إشراف" };
const label = (map: Record<string, string>, value: unknown) => map[String(value)] ?? String(value ?? "غير محدد");
const formatDate = (value: unknown) => {
  const date = new Date(String(value ?? ""));
  return Number.isNaN(date.getTime()) ? "وقت غير محدد" : `${date.toLocaleDateString("ar-SA")} ${date.toLocaleTimeString("ar-SA", { hour: "2-digit", minute: "2-digit" })}`;
};

export default function AuditLog() {
  const [page, setPage] = useState(1); const [action, setAction] = useState(""); const [targetType, setTargetType] = useState(""); const [open, setOpen] = useState<string | null>(null);
  const api = trpc.admin as any;
  const q = api.auditLogsList.useQuery({ page, action: action || undefined, targetType: targetType || undefined }, { retry: 1 });
  const { colors } = useTheme();
  if (q.isLoading) return <AdminFrame title="سجل التدقيق"><LoadingState /></AdminFrame>;
  if (q.error) return <AdminFrame title="سجل التدقيق"><ErrorState onRetry={() => void q.refetch()} /></AdminFrame>;
  const d = (q.data ?? {}) as any, rows = Array.isArray(d.rows) ? d.rows : [], totalPages = Math.max(1, Math.ceil(Number(d.total ?? rows.length) / Number(d.pageSize ?? (rows.length || 1))));
  const cycle = (current: string, values: string[], setter: (v: string) => void) => setter(values[(values.indexOf(current) + 1) % values.length] ?? "");
  const actionValues = ["", ...(Array.isArray(d.actions) ? d.actions : Object.keys(actions))], targetValues = ["", ...(Array.isArray(d.targetTypes) ? d.targetTypes : Object.keys(targets))];
  return <AdminFrame title="سجل التدقيق"><Card accent><Text style={[styles.heading, { color: colors.text }]}>سجل إجراءات الإشراف</Text><Text style={[styles.small, { color: colors.muted }]}>كل إجراءات الإشراف مسجّلة هنا بترتيب زمني تنازلي — من فعل ماذا ومتى.</Text></Card>
     <View style={styles.filters}><Pressable onPress={() => { cycle(action, actionValues, (v) => { setAction(v); setPage(1); }); }} style={[styles.filter, { borderColor: colors.border }]}><Text style={[styles.small, { color: colors.text }]}>{action ? label(actions, action) : "كل الإجراءات"}</Text></Pressable><Pressable onPress={() => { cycle(targetType, targetValues, (v) => { setTargetType(v); setPage(1); }); }} style={[styles.filter, { borderColor: colors.border }]}><Text style={[styles.small, { color: colors.text }]}>{targetType ? label(targets, targetType) : "كل المستهدفات"}</Text></Pressable>{action || targetType ? <Pressable onPress={() => { setAction(""); setTargetType(""); setPage(1); }}><Text style={[styles.small, { color: colors.primary }]}>إزالة التصفية</Text></Pressable> : null}<Text style={[styles.small, { color: colors.muted }]}>{String(d.total ?? rows.length)} سجلاً</Text></View>
     {!rows.length ? <EmptyState title="لا توجد سجلات" description="لم تُسجّل إجراءات مطابقة للفلاتر." icon="list-outline" /> : <Card>{rows.map((r: any) => <View key={String(r.id)} style={[styles.entry, { borderBottomColor: colors.border }]}><Pressable onPress={() => setOpen(open === String(r.id) ? null : String(r.id))}><View style={styles.line}><Text style={[styles.title, { color: colors.primary }]}>{label(actions, r.action)}</Text><Badge label={label(targets, r.targetType)} /><Text style={[styles.small, { color: colors.muted }]}>{String(r.adminName ?? r.adminUsername ?? "مشرف محذوف")}</Text></View><Text style={[styles.small, { color: colors.muted }]}>{formatDate(r.createdAt)}</Text></Pressable>{open === String(r.id) ? <View style={styles.details}><Text style={[styles.small, { color: colors.muted }]}>المستهدف: {r.targetId ? String(r.targetId) : "لا يوجد"}</Text>{r.ipAddress ? <Text style={[styles.small, { color: colors.muted }]}>عنوان الشبكة: {String(r.ipAddress)}</Text> : null}{r.details != null ? <Text selectable style={[styles.json, { color: colors.muted }]}>{JSON.stringify(r.details, null, 2)}</Text> : !r.targetId && !r.ipAddress ? <Text style={[styles.small, { color: colors.muted }]}>لا تفاصيل إضافية</Text> : null}</View> : null}</View>)}</Card>}
    {totalPages > 1 ? <View style={styles.pagination}><Pressable disabled={page <= 1} onPress={() => setPage(page - 1)}><Text style={[styles.small, { color: page <= 1 ? colors.muted : colors.primary }]}>السابق</Text></Pressable><Text style={[styles.small, { color: colors.muted }]}>صفحة {page} من {totalPages}</Text><Pressable disabled={page >= totalPages} onPress={() => setPage(page + 1)}><Text style={[styles.small, { color: page >= totalPages ? colors.muted : colors.primary }]}>التالي</Text></Pressable></View> : null}
  </AdminFrame>;
}
const styles = StyleSheet.create({ heading: { fontFamily: "IBMPlexSansArabic_700Bold", fontSize: 19, textAlign: "right" }, small: { fontFamily: "IBMPlexSansArabic_400Regular", fontSize: 12, textAlign: "right", lineHeight: 20 }, filters: { flexDirection: "row-reverse", gap: 8, marginVertical: 10, alignItems: "center", flexWrap: "wrap" }, filter: { flex: 1, borderWidth: 1, borderRadius: 14, padding: 10, alignItems: "center" }, entry: { paddingVertical: 11, borderBottomWidth: StyleSheet.hairlineWidth }, line: { flexDirection: "row-reverse", alignItems: "center", gap: 8, flexWrap: "wrap" }, title: { fontFamily: "IBMPlexSansArabic_700Bold", fontSize: 13 }, details: { marginTop: 7, gap: 3, paddingRight: 8 }, json: { fontFamily: "monospace", fontSize: 10, textAlign: "left", backgroundColor: "#00000008", padding: 8 }, pagination: { flexDirection: "row-reverse", justifyContent: "center", alignItems: "center", gap: 25, marginTop: 14 } });