import { useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { AdminFrame, AdminInput, safeError } from "./_common";
import { Button, Card, EmptyState, ErrorState, LoadingState } from "../../components/ui";
import { trpc } from "../../lib/trpc";
import { useTheme } from "../../lib/theme";
import { useAuth } from "../../lib/auth";
import { useRouter } from "expo-router";
import { isNonWhitespacePassword } from "../../../../lib/tabyan-trpc/src/lib/password-validation";
import { normalizeDigits } from "../../../../lib/tabyan-trpc/src/lib/input-normalization";
export default function Settings() {
  const { colors } = useTheme(); const utils = trpc.useUtils(); const { signOut } = useAuth(); const router = useRouter(); const q = trpc.admin.settingsGet.useQuery(); const [key, setKey] = useState(""); const [value, setValue] = useState(""); const [current, setCurrent] = useState(""); const [password, setPassword] = useState(""); const [surah, setSurah] = useState(""); const [ayah, setAyah] = useState(""); const [feedback, setFeedback] = useState("");
  const todayVerse = trpc.dailyVerse.today.useQuery();
  const versePreview = trpc.dailyVerse.preview.useQuery({ surahNumber: Number(surah), ayahNumber: Number(ayah) }, { enabled: Number(surah) >= 1 && Number(surah) <= 114 && Number(ayah) >= 1, retry: 0 });
  const update = trpc.admin.settingsUpdate.useMutation({ onSuccess: () => { setFeedback("حُفظ الإعداد"); void utils.admin.settingsGet.invalidate(); }, onError: (e: unknown) => setFeedback(safeError(e, "تعذر حفظ الإعداد.")) }); const change = trpc.admin.settingsChangeMasterPassword.useMutation({ onSuccess: async () => { setFeedback("غُيّرت كلمة المرور الرئيسية — سيُسجّل خروج المشرفين"); await signOut(); router.replace("/"); }, onError: (e: unknown) => setFeedback(safeError(e, "تعذر تغيير كلمة المرور.")) }); const verse = trpc.dailyVerse.set.useMutation({ onSuccess: () => { setFeedback("اعتُمدت آية اليوم"); setSurah(""); setAyah(""); void utils.dailyVerse.today.invalidate(); }, onError: (e: unknown) => setFeedback(safeError(e, "تعذر اعتماد الآية.")) }); const clearVerse = trpc.dailyVerse.clear.useMutation({ onSuccess: () => { setFeedback("أُلغي تخصيص آية اليوم"); void utils.dailyVerse.today.invalidate(); }, onError: (e: unknown) => setFeedback(safeError(e, "تعذر إلغاء تخصيص الآية.")) });
  if (q.isLoading) return <AdminFrame title="الإعدادات"><LoadingState /></AdminFrame>; if (q.error) return <AdminFrame title="الإعدادات"><ErrorState onRetry={() => void q.refetch()} /></AdminFrame>;
  const labels: Record<string, string> = { login_max_attempts: "الحد الأقصى لمحاولات الدخول", login_block_duration_hours: "مدة حظر الدخول بالساعات", placement_video_duration_seconds: "مدة فيديو اختبار تحديد المستوى بالثواني", placement_review_deadline_hours: "مهلة مراجعة اختبار تحديد المستوى", promotion_video_duration_seconds: "مدة فيديو الترقية بالثواني", fatwa_reassign_hours: "مهلة إعادة إسناد الفتوى بالساعات", recording_retention_months: "مدة الاحتفاظ بالتسجيلات بالأشهر", notif_ayah_time: "وقت إشعار الآية", notif_hadith_time: "وقت إشعار الحديث", notif_ibn_qayyim_time: "وقت إشعار ابن القيم", notif_review_reminder_time: "وقت تذكير المراجعة" };
  const rows: any[] = (Array.isArray(q.data) ? q.data : []).filter((s) => labels[s.key]);
  return <AdminFrame title="الإعدادات"><Text style={[styles.feedback, { color: colors.primary }]}>{feedback}</Text>
    <Card><Text style={[styles.title, { color: colors.text }]}>الإعدادات التشغيلية</Text>{!rows.length ? <EmptyState title="لا توجد إعدادات قابلة للتعديل" /> : rows.map((s) => <Button key={s.key} label={`${labels[s.key]}: ${String(s.value ?? "")}`} variant="secondary" onPress={() => { setKey(s.key); setValue(String(s.value ?? "")); }} />)}{key ? <><Text style={[styles.title, { color: colors.text }]}>{labels[key] ?? "الإعداد"}</Text><AdminInput value={value} onChangeText={setValue} placeholder="القيمة الجديدة" /><Button label="حفظ" loading={update.isPending} onPress={() => update.mutate({ key, value } as any)} /></> : null}</Card>
    <Card><Text style={[styles.title, { color: colors.text }]}>كلمة المرور الرئيسية</Text><AdminInput value={current} onChangeText={setCurrent} placeholder="الحالية" /><AdminInput value={password} onChangeText={setPassword} placeholder="أدخل كلمة المرور الجديدة" /><Button label="تغيير كلمة المرور" disabled={!isNonWhitespacePassword(password) || !isNonWhitespacePassword(current)} onPress={() => change.mutate({ current, newPassword: password } as any)} /></Card>
     <Card><Text style={[styles.title, { color: colors.text }]}>آية اليوم</Text>{todayVerse.data?.verse ? <Text style={[styles.verse, { color: colors.text }]}>﴿ {todayVerse.data.verse.text} ﴾{"\n"}سورة {todayVerse.data.verse.surahName}، آية {todayVerse.data.verse.ayahNumber}{todayVerse.data.verse.source === "admin" ? " — مخصصة من الإدارة" : " — اختيار تلقائي"}</Text> : null}<AdminInput value={surah} onChangeText={(value) => setSurah(normalizeDigits(value).replace(/\D/g, ""))} placeholder="رقم السورة (1-114)" keyboardType="number-pad" /><AdminInput value={ayah} onChangeText={(value) => setAyah(normalizeDigits(value).replace(/\D/g, ""))} placeholder="رقم الآية" keyboardType="number-pad" />{versePreview.data ? <Text style={[styles.preview, { color: colors.text }]}>﴿ {versePreview.data.text} ﴾{"\n"}سورة {versePreview.data.surahName}، آية {versePreview.data.ayahNumber}</Text> : null}<View style={styles.actions}><Button label="اعتماد آية اليوم" disabled={!versePreview.data || verse.isPending} loading={verse.isPending} onPress={() => verse.mutate({ surahNumber: Number(surah), ayahNumber: Number(ayah) })} />{todayVerse.data?.verse.source === "admin" ? <Button label="إلغاء التخصيص" variant="secondary" disabled={clearVerse.isPending} onPress={() => clearVerse.mutate({})} /> : null}</View></Card>
    <Card><Text style={[styles.title, { color: colors.text }]}>الجلسة</Text><Button label="تسجيل الخروج" variant="danger" icon="log-out-outline" onPress={() => void signOut().then(() => router.replace("/"))} /></Card>
  </AdminFrame>;
}
const styles = StyleSheet.create({ title: { fontFamily: "IBMPlexSansArabic_700Bold", fontSize: 17, textAlign: "right", marginBottom: 10 }, feedback: { fontFamily: "IBMPlexSansArabic_600SemiBold", textAlign: "right", marginBottom: 8 }, verse: { textAlign: "right", lineHeight: 26, marginBottom: 10 }, preview: { textAlign: "right", lineHeight: 26, marginBottom: 10 }, actions: { gap: 8 } });